### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by ghost** [akka-4/22clin#1]
I have been curious about How to deploy this project. You can deploy using Heroku or Vercel or Github Pages. I recommend Github Pages. Because Heroku is not for client project and Vercel is for the client project that use React.js or Next.js. And, Github Pages is very easy to deploy your project to be globally.

Which one do you want to deploy? And, if you have the others way to deploy, please share to me @akka-4.

**Comment by akka-4** [comment]
I was originally going to use a Vercel, but after seeing your comment, I think it would be easiest to use Github pages

**Comment by ghost** [comment]
Hmm.. nice choice.

But! Github has one bad point.
That is.. you can only deploy this website to `https://akka-4.github.io/22-clin`. So, if you create a router which is like `/create`, then user have to go to the `https://akka-4.github.io/22-clin/create` to see the `/create` router.

So, many people who want to create own website or portfolio website deploy using github pages, but in this case, I did not know it then, but now that I think of it, it is better if it will be deployed by Vercel.

Sorry, Vercel is better choice if you wanted to deploy this website using Vercel at all first.

**Comment by akka-4** [comment]
Should I learn another language if I want to use vercel?

**Comment by ghost** [comment]
Nope. You do not need. But you should study about how to configure your project to deploy to Vercel. It is easy to study. Search about `how to configure in Vercel` like this, and read documentations that is written by Vercel company.

**Comment by ghost** [comment]
In vercel, they have supported a lot of ways which are likes React.js, Next.js and Nuxt.js.. so you have to study correctly. Sometimes, many people wasted their times because they studied incorrectly.

**Comment by akka-4** [comment]
My test has finished.
So I can make website!!

**Comment by akka-4** [comment]
To summarize what I need to do in the future, first, I want to license MIT to my code, and secondly, I want to distribute it using VER to distribute it.

**Comment by ghost** [comment]
Ok. But what is VER?

**Comment by akka-4** [comment]
Oh sorry...

VER means Vercel...

**Comment by ghost** [comment]
Ok, then what does `distribute` mean?

**Comment by akka-4** [comment]
Umm...
Distribute means publish

**Comment by ghost** [comment]
Does distributing mean publishing?? Ok..

**Comment by ghost** [comment]
Then, the one thing that I have thought about publishing error in the Vercel, You did not configure the root pages and router pages properly. So, I will create a Pull Request to solve that problem. I think that I will just move the path of the html files to solve it. Which means, you should republish it again. (Maybe the Vercel bot in the Github will help.)

**Comment by akka-4** [comment]
Okay!! Thank you!!

**Comment by ghost** [comment]
Oh, I found the method to solve it without creating a pull request. [See](https://vercel.com/docs/concepts/edge-network/directory-listing) Here!

**Comment by akka-4** [comment]
So...should i add some code in html documents?

**Comment by ghost** [comment]
Ah,... See https://vercel.com/docs/concepts/edge-network/directory-listing <- Here

**Comment by ghost** [comment]
Or, the way to deploy might be wrong, So, [This page](https://deliverystack.net/2021/11/04/deploy-a-static-file-website-to-vercel/) will help you to deploy a static page.

**Comment by ghost** [comment]
I think you should change some configurations of Vercel.

**Comment by ghost** [comment]
Look [here](https://vercel.com/docs/concepts/edge-network/directory-listing#toggling-directory-listing) and change the configurations of vercel

**Comment by akka-4** [comment]
What is the main cause of these errors now? I don't quite understand...

**Comment by ghost** [comment]
Well... I do not know about that too. Because I have ever used Vercel, but I have never had any error in process of deploying. So, I think that there is the problem in something like personal configuration or this project.

**Comment by ghost** [comment]
Ok... I will one more.. really last try to be successful in deploying. I will merge it tomorrow.

**Comment by ghost** [comment]
OH!!! I found the specific error! That is about the routing as you can see in the other comments. But, if you control some of the configurations, this project will be getting nicer, but it is ok.

**Comment by ghost** [comment]
Error was solved with #11
