### ISSUE TITLE
readmes

### ISSUE THREAD

**Issue by ghost** [akka-4/22clin#3]
There is a `README.md` in the root directory. Then it has two descriptions, Korean and English. In this case, it is better if it has two separated files I think. One is for Korean and the other is for English. I recommend you to set Korean version as main README.md. Because it is for Korean people. How do you think about @akka-4?

**Comment by akka-4** [comment]
Umm....I understand your comment. 
So I'll  make a new files for korean, after I come back to my home :)

**Comment by akka-4** [comment]
How can I make new README.md file?

**Comment by ghost** [comment]
If you want to create Korean version as main, create README.md file and write contents in Korean. And create en.md file and write contents in English. And then, add a link each other on the end part of each file to make user to see the English version README.md.

**Comment by ghost** [comment]
After that, commit and push to GitHub. Then, the visitor will be able to see the Korean as main and English version.

**Comment by akka-4** [comment]
Okay. Thank you So Seol. I'll  try that!!
:)

**Comment by ghost** [comment]
I am so sorry.. but my name is Seol So. Not So Seol.

**Comment by ghost** [comment]
It was solve by #7

**Comment by akka-4** [comment]
Oh....I'm sorry about that...

It seems that such a mistake occurred because it was used in the order of
words used in Korea. I'll be careful from now on.



2022년 9월 20일 (화) 오전 3:08, Seol So ***@***.***>님이 작성:
