### ISSUE TITLE
Contents

### ISSUE THREAD

**Issue by ghost** [akka-4/22clin#4]
Hey, @akka-4. Is here all of the contents that you want to express?

**Comment by ghost** [comment]
If it was done, Separate html and css files to see more easily as well. And I can help you to create a Pull Request about it. Or not, I think you have to fill all of the contents.

**Comment by akka-4** [comment]
It is not the final version yet, and several revisions are expected in the future.
The work is being done by Yejun and I, and when it is done, I will separate CSS and HTML.

**Comment by ghost** [comment]
Nice, The reason that I asked to you is because it has not been committed. Thanks for answering
