### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ghost** [akka-4/22clin#6]
Which LICENSE is this service base on? This service must be licensed to protect this code from dangerous things. There are a lot of licenses, and I recommend you use the MIT license that many people use.

**Comment by akka-4** [comment]
Does MIT have its own strengths?

**Comment by ghost** [comment]
Hmm... You can more details about MIT License [here](https://opensource.org/licenses/MIT)

**Comment by akka-4** [comment]
I've been googling and the MIT license looks the best. It would be nice to proceed with the MIT license.


I'll find how to add MIT license :D

**Comment by ghost** [comment]
Nonono. You do not need to search how to add MIT License. You just but `MIT` string which is matched to `license` key in `package.json`. As you can see, there is a key and value set in `package.json`.

```json
{
  "license": "MIT"
}
```

You already do it 😄

**Comment by akka-4** [comment]
Aha!!

So...

I put that code in head tag???

**Comment by akka-4** [comment]
Hmm...
I just put them in this repository as text file??

**Comment by ghost** [comment]
No.

As you can see in `package.json`, there are a lot of key and value sets. In a key, there is a `license` and `MIT` as a value. So, this project have been MIT licensed project since this project was created.(since I created `package.json`)

You do not have to do anything to add MIT license.
